import 'dart:convert';
import 'package:uuid/uuid.dart';
import 'seat_layout.dart';

/// One bus rented for a tour.
///
/// Buses are children of a Tour (1 tour → many buses). The agent enters
/// these once the bus owner has confirmed availability.
class BusDetails {
  final String id;
  final String? tourId;

  /// Display name on the tour, e.g. "Bus 1", "Bus 2". Auto-generated by the
  /// add flow but editable.
  final String name;

  final String busNumber;
  final String driverName;
  final String driverPhone;
  final String? ownerName;
  final String? ownerPhone;
  final bool isAC;
  final String busType;
  final int totalSeats;
  final String? notes;

  /// Visual seat layout (lower + upper deck) used for assignment. Nullable
  /// while a bus is being created and before the layout editor is filled.
  final BusLayout? layout;

  BusDetails({
    String? id,
    this.tourId,
    String? name,
    required this.busNumber,
    required this.driverName,
    required this.driverPhone,
    this.ownerName,
    this.ownerPhone,
    this.isAC = true,
    this.busType = 'Semi-Sleeper',
    required this.totalSeats,
    this.notes,
    this.layout,
  })  : id = id ?? const Uuid().v4(),
        name = name ?? 'Bus';

  /// Effective capacity — prefers the visual layout, falls back to the
  /// legacy `totalSeats` count.
  int get effectiveCapacity => layout?.totalSeats ?? totalSeats;

  Map<String, dynamic> toAppwrite(String tourId) {
    return {
      'tourId': tourId,
      'name': name,
      'busNumber': busNumber,
      'driverName': driverName,
      'driverPhone': driverPhone,
      'ownerName': ownerName,
      'ownerPhone': ownerPhone,
      'isAC': isAC,
      'busType': busType,
      'totalSeats': totalSeats,
      'notes': notes,
      'layout': layout != null ? jsonEncode(layout!.toMap()) : null,
    };
  }

  factory BusDetails.fromAppwrite(Map<String, dynamic> map) {
    return BusDetails(
      id: ((map[r'$id'] ?? map['id']) as String?) ?? const Uuid().v4(),
      tourId: map['tourId'] as String?,
      name: (map['name'] as String?)?.trim().isNotEmpty == true
          ? map['name'] as String
          : 'Bus',
      busNumber: map['busNumber'] as String? ?? '',
      driverName: map['driverName'] as String? ?? '',
      driverPhone: map['driverPhone'] as String? ?? '',
      ownerName: map['ownerName'] as String?,
      ownerPhone: map['ownerPhone'] as String?,
      isAC: map['isAC'] as bool? ?? true,
      busType: map['busType'] as String? ?? 'Semi-Sleeper',
      totalSeats: map['totalSeats'] as int? ?? 0,
      notes: map['notes'] as String?,
      layout: _parseLayout(map['layout']),
    );
  }

  static BusLayout? _parseLayout(dynamic value) {
    if (value == null) return null;
    if (value is String && value.isNotEmpty) {
      try {
        final decoded = jsonDecode(value);
        if (decoded is Map) {
          return BusLayout.fromMap(Map<String, dynamic>.from(decoded));
        }
      } catch (_) {
        return null;
      }
    }
    if (value is Map) {
      return BusLayout.fromMap(Map<String, dynamic>.from(value));
    }
    return null;
  }

  BusDetails copyWith({
    String? name,
    String? busNumber,
    String? driverName,
    String? driverPhone,
    String? ownerName,
    String? ownerPhone,
    bool? isAC,
    String? busType,
    int? totalSeats,
    String? notes,
    BusLayout? layout,
  }) {
    return BusDetails(
      id: id,
      tourId: tourId,
      name: name ?? this.name,
      busNumber: busNumber ?? this.busNumber,
      driverName: driverName ?? this.driverName,
      driverPhone: driverPhone ?? this.driverPhone,
      ownerName: ownerName ?? this.ownerName,
      ownerPhone: ownerPhone ?? this.ownerPhone,
      isAC: isAC ?? this.isAC,
      busType: busType ?? this.busType,
      totalSeats: totalSeats ?? this.totalSeats,
      notes: notes ?? this.notes,
      layout: layout ?? this.layout,
    );
  }
}
