import '../models/bus_type.dart';
import '../models/seat_layout.dart';

/// Outcome of trying to rebuild a bus seat layout that was lost from the
/// `buses.layout` jsonb column.
class LayoutRecovery {
  /// The rebuilt layout, or null when the evidence could not identify exactly
  /// one. NEVER a best guess — see [reason].
  final BusLayout? layout;

  /// Plain-language account of what happened, safe to print in a repair report.
  final String reason;

  /// Every distinct layout that can host all the surviving seat ids, ordered by
  /// the generator inputs that produced them.
  ///
  /// Populated even when [recovered] is false, because these are genuinely
  /// useful: by construction EVERY candidate re-attaches EVERY surviving
  /// assignment identically — they differ only in seats nobody is sitting in.
  /// A repair operator can therefore be shown the shortlist and pick, rather
  /// than being told only that it failed.
  final List<BusLayout> candidates;

  /// How many distinct candidate layouts matched the evidence. `1` is the only
  /// value that yields a [layout]; more means ambiguity, zero means the
  /// surviving ids fit no valid layout of this bus.
  int get candidateCount => candidates.length;

  /// Surviving seat ids that NO candidate layout could host. Non-empty here
  /// means the inputs are inconsistent — wrong bus, wrong seat count, or ids
  /// from a layout generated by a different seat engine.
  final List<String> unmatched;

  const LayoutRecovery({
    this.layout,
    required this.reason,
    this.candidates = const [],
    this.unmatched = const [],
  });

  bool get recovered => layout != null;
}

/// Rebuild the seat layout of a bus whose `layout` jsonb was destroyed, using
/// the seat ids that survive in its passengers' `assigned_seats`.
///
/// This is repair tooling for a specific data loss: a whole-row bus write made
/// before the lazily-fetched layout had loaded nulled the column, leaving
/// `total_seats` and every seat assignment behind but no grid for them to point
/// at. See migration 065 for the guard that stops it recurring.
///
/// It works because [BusLayout.generate] is deterministic and seat ids are
/// `prefix + row-major index`: regenerating with the ORIGINAL inputs reproduces
/// the ORIGINAL ids, so every assignment re-attaches with nothing rewritten.
/// The original inputs are not recorded anywhere, so they are inferred by
/// generating every layout the bus could plausibly have had and keeping only
/// those that can host all of [assignedSeatIds].
///
/// SAFETY: this returns a layout ONLY when exactly one candidate survives.
/// Ambiguous or contradictory evidence yields `recovered == false` with a
/// [LayoutRecovery.reason], because a wrong grid would silently move real
/// passengers into seats they never booked. Refusing is always the correct
/// failure mode here — a Supabase backup restore is the fallback.
LayoutRecovery recoverBusLayout({
  required int totalSeats,
  required BusType busType,
  required Set<String> assignedSeatIds,
  int seaterCount = 0,
}) {
  if (totalSeats <= 0) {
    return const LayoutRecovery(
      reason: 'bus has no total_seats to rebuild from',
    );
  }
  if (assignedSeatIds.isEmpty) {
    return const LayoutRecovery(
      reason: 'no surviving seat assignments to infer the layout from',
    );
  }

  // Candidate space. `singleSofaCount` is the only real degree of freedom;
  // `allDoubleBackRow` reshapes the last row and therefore the row-major
  // numbering, so both settings must be tried. (`hasBalcony` is a documented
  // no-op on the generator and is not varied.)
  final matches = <String, BusLayout>{};
  final hostable = <String>{};

  for (var singles = 0; singles <= totalSeats; singles++) {
    for (final backRow in const [false, true]) {
      final candidate = BusLayout.generate(
        busType: busType,
        totalSeats: totalSeats,
        seaterCount: seaterCount,
        singleSofaCount: singles,
        allDoubleBackRow: backRow,
      );
      // The generator conserves the berth count, but clamping inside it means
      // several `singles` values can collapse onto the same layout; a mismatch
      // here would mean the bus never had this seat count at all.
      if (candidate.totalSeats != totalSeats) continue;

      final ids = candidate.allSeatIds.toSet();
      hostable.addAll(ids);
      if (!ids.containsAll(assignedSeatIds)) continue;

      // Key by the id SET, so two parameter combinations that produce the very
      // same grid count as one candidate rather than a false ambiguity.
      final key = (candidate.allSeatIds.toList()..sort()).join(',');
      matches[key] = candidate;
    }
  }

  if (matches.isEmpty) {
    final unmatched = assignedSeatIds.where((id) => !hostable.contains(id));
    return LayoutRecovery(
      reason: 'no candidate layout of $totalSeats berths can host every '
          'surviving seat id',
      unmatched: (unmatched.toList()..sort()),
    );
  }

  if (matches.length > 1) {
    return LayoutRecovery(
      reason: 'ambiguous — ${matches.length} different layouts all fit the '
          'surviving seat ids; they differ only in seats nobody occupies, so '
          'every one of them re-attaches all ${assignedSeatIds.length} '
          'assignments — pick one rather than letting this guess',
      candidates: matches.values.toList(),
    );
  }

  return LayoutRecovery(
    layout: matches.values.first,
    reason: 'rebuilt from ${assignedSeatIds.length} surviving seat ids',
    candidates: matches.values.toList(),
  );
}
